version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: reservations_db
      POSTGRES_USER: reservations_db_user
      POSTGRES_PASSWORD: 123456@reservations_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: reservations_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reservations_db
      SPRING_DATASOURCE_USERNAME: reservations_db_user
      SPRING_DATASOURCE_PASSWORD: 123456@reservations_db_password
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
volumes:
  postgres_data: